Fix for "NoMethodError (undefined method `code' for #<String>)" error.
Changed active_shipping dependency to '>= 0.9.11' because in 0.9.3, the
request method in active_shipping-0.9.3/lib/active_merchant/common/connection.rb returned
a string, which becomes the return value for raw_ssl_request in
activemerchant-1.12.0/lib/active_merchant/common/posts_data.rb.

But in handle_response (in activemerchant-1.12.0/lib/active_merchant/common/posts_data.rb),
it expects an actual response object (such as Net::HTTPOK), that
responds to code.

This appears to have been fixed in activemerchant since this commit:

commit 5a857a69860ef7c8240080d261054b024a7ee7c8
Author: Dennis Theisen <dennis@shopify.com>
Date:   Mon Dec 13 09:48:55 2010 -0500

    Updated common files with changes from activemerchant

@@ -71,9 +71,8 @@ module ActiveMerchant
           end

           info "--> %d %s (%d %.4fs)" % [result.code, result.message, result.body ? result.body.length : 0, realtime], tag
-          response = handle_response(result)
-          debug response
-          response
+          debug result.body
+          result